### ISSUE TITLE
Launching Isaac Sim in extention workflow takes painfully long and failed

### ISSUE THREAD

**Issue by Guanbin-Huang** [NVIDIA-Omniverse/OmniIsaacGymEnvs#104]
i run this:
./isaac-sim.gym.sh --ext-folder /home/lr/OmniIsaacGymEnvs/omniisaacgymenvs

<img width="1070" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/d2d39063-a4fc-4e50-8fe6-0600def8185f">

<img width="548" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/ed58d232-c3d0-4b49-99da-aebb185f0b79">

<img width="533" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/9d453832-ec51-4822-b0f0-2792a44368a1">

**Comment by Guanbin-Huang** [comment]
i also tried this.

<img width="1084" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/a9bdf021-4710-4134-aec3-0cb9532b416d">

**Comment by Guanbin-Huang** [comment]
i also tryied this 

./isaac-sim.gym.sh --ext-folder /home/lr/OmniIsaacGymEnvs

<img width="991" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/54c8780c-8018-4374-8682-8be057ffe58c">

<img width="429" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/38dba098-4a0c-42af-bb86-2aaf1c57a348">

<img width="1023" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/926eb2c9-e428-4666-9dea-970ee4c33282">

<img width="879" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/6bd88652-cbf4-4459-8223-a5a68efb7768">

**Comment by kellyguo11** [comment]
Hi there, the extension name should be `OmniIsaacGymEnvs` (camel case), which should be fixed in the latest isaac sim 2023.1.0-hotfix.1 release. The `--ext-folder` flag should point to the parent directory of `OmniIsaacGymEnvs`, which in your case would be `/home/lr`

**Comment by Guanbin-Huang** [comment]
I follow your advice and I run the following command:
<img width="786" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/7eaae37a-af28-4934-9f48-b60e912551db">

after i modify the omni.isaac.sim.gym.kit, i use the pip install -e . (not sure it's used for updating the pkg?)
<img width="550" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/97af0fd2-d2c9-4376-83ae-3639d3ae24e1">

then the log said
<img width="1026" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/c5c604e8-27aa-4da7-be4a-59abaa5fa1f2">
<img width="983" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/cf78affd-b946-4261-bb85-cd2e339882fc">
<img width="1055" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/c5a6ed54-227d-4a4c-94f2-032edcbae502">
<img width="875" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/34c9003d-d731-4a47-bb08-117e0da679fb">

**Comment by kellyguo11** [comment]
Hi there, please use the Isaac Sim 2023.1.0-hotfix.1 release with the latest OmniIsaacGymEnvs repo (2023.1.0b), or with the Isaac Sim 2023.1.0 release (not including the hot fix), you can use the OmniIsaacGymEnvs 2023.1.0a release. You can try adding back the `"psutil==5.9.3"` dependency to setup.py, which should not be needed anymore with the hotfix Isaac Sim release.

**Comment by Guanbin-Huang** [comment]
<img width="832" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/0a81c09b-907a-4da5-b697-cc66bedde395">
<img width="440" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/1f62f006-855a-4425-9b30-1096acfd6ac1">
I already uninstall the old version and install the latest version(this is what you name "Hot Fix" isaac sim release.) and I git clone the lastest version of omniverse isaac gym by 
git clone https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs.git

**Comment by Guanbin-Huang** [comment]
even i'm using the the latest version. I still got the errors:

<img width="746" alt="image" src="https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/51700575-5d09-4419-9ce5-88caf8eed061">

No module named "psutils and six"

![Uploading image.png…]()

**Comment by Guanbin-Huang** [comment]
I managed to fix the bug in a very hardcode way as followed
for each failed script due to lack of psutil or six

1. first i make sure which python env i'm using for isaac sim-2023.1.0-hotfix.
and i add the path of python packages into all failed script like the following

![image](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/6a744c45-861b-42ec-bd7d-7f8ce0a74dbf)


![image](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/30463291/06992985-de4f-4525-9109-e6b93ee14a3f)
let's say the file saying no module xxxx is extests.py. 

i desire a more scientific solution to fix it.

**Comment by XEL-Maker** [comment]
@kellyguo11
Hi 
I face with the same problem as like above.
I'm using Window 11 with Isaac Sim 2023.1.0-hotfix.1.
I've tried bot 2023.1.0 and 2023.1.0-hotfix.1 and the result was 2023.1.0 can not open 
2023.1.0-hotfix.1 is same as above image wiht "no examlple button"
Below is the error at 2023.1.0.
![2023_1_0](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/52307315/3073f671-e336-4ffc-984a-b502fa737232)

**Comment by Guanbin-Huang** [comment]
> @kellyguo11 Hi I face with the same problem as like above. I'm using Window 11 with Isaac Sim 2023.1.0-hotfix.1. I've tried both 2023.1.0 and 2023.1.0-hotfix.1 and the result was 2023.1.0 can not open 2023.1.0-hotfix.1 is same as above image wiht "no examlple button" Below is the error at 2023.1.0. ![2023_1_0](https://user-images.githubusercontent.com/52307315/282392057-3073f671-e336-4ffc-984a-b502fa737232.png)

follow what i've done. you can fix it in a not so decent way.

**Comment by kellyguo11** [comment]
Does it work for you if you add the missing dependencies, such as `"psutil==5.9.3"` into setup.py and re-run `pip install -e .`? or try running `pip install -e . --force-reinstall` to make sure all of the required libraries get installed.

**Comment by XEL-Maker** [comment]
@kellyguo11
I solved it using the solution you suggested.
For some reason, it seems that the Python specified by doskey was not 3.10.
I think the cause of the problem is that multiple versions of Isaac Sim and Python are installed.
My problem has been solved.
@Guanbin-Huang I think my problem was a little different from yours.
After correcting the Python path and reinstalling, the OIGE package was additionally installed and began to operate normally.
My issue has been resolved.
Please close if your issue has been resolved.

**Comment by Guanbin-Huang** [comment]
> @kellyguo11 I solved it using the solution you suggested. For some reason, it seems that the Python specified by doskey was not 3.10. I think the cause of the problem is that multiple versions of Isaac Sim and Python are installed. My problem has been solved. @Guanbin-Huang I think my problem was a little different from yours. After correcting the Python path and reinstalling requirements, the OIGE package was additionally installed and began to operate normally. My issue has been resolved. Please close if your issue has been resolved.

actually, my issue is not yet solved. Cuz now i used hard coding. Not a general solution.
